//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Sample Team Tools.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Extensions.DependencyInjection;

namespace Sample.BLLayer.BLUtilities.Extensions
{
 
    public static class EntityExtensions
    {

        public static void AddEntityServicesToConfigure(this IServiceCollection services)
        {
            AddRepositriesToScope(services);
            AddMappingToScope(services);
            AddValidatingToScope(services);
            AddQueryServicesToScope(services);
            AddUpdateServicesToScope(services);
        }

        private static void AddRepositriesToScope(IServiceCollection services)
        {
             
       
        }

        private static void AddValidatingToScope(IServiceCollection services)
        {
             
       
        }

        private static void AddMappingToScope(IServiceCollection services)
        {
             
       
        }

        private static void AddUpdateServicesToScope(IServiceCollection services)
        {
             
       
        }

        private static void AddQueryServicesToScope(IServiceCollection services)
        {
             
       
        }
    }
}
