using System;
using System.IO;
using System.Linq;
using System.Text;
using Sample.AutoGenerated.GeneratedStructure.T4GeneratedServices.T4GenratedMainService;

namespace Sample.AutoGenerated
{
    public class Program
    {
        private static void Main()
        {
            new T4GeneratedMainService().ExecuteAutoGenerated();
        }
    }
}
