using System;
using Sample.AutoGenerated.HelperClasses.Interfaces;
using System.Collections.Generic;

namespace Sample.AutoGenerated.GeneratedStructure.ClassesGeneratedStructure
{
    public partial class EntitiesAutoMapperTemplate : ITextTemplate
    {

        /// <summary>
        /// Entity's Namespace.
        /// </summary>
        public string NameSpace { get; }

        /// <summary>
        /// Entity Files.
        /// </summary>
        public IEnumerable<string> EntityFiles { get; }

        /// <summary>
        /// AutoMapper Name.
        /// </summary>
        public string AutoMapperName { get; }

        /// <summary>
        /// Profile.
        /// </summary>
        public Type Profile { get; }

        /// <summary>
        /// Creates an Instance of TableEntityTemplate.
        /// </summary>
        /// <param name="nameSpace">Entity's Namespace.</param>
        /// <param name="profile">Profile.</param>
        /// <param name="autoMapperName">AutoMapper Name.</param>
        /// <param name="entities">Entities.</param>
        public EntitiesAutoMapperTemplate(string nameSpace, string autoMapperName, Type profile, IEnumerable<string> entityFiles)
            => (NameSpace, AutoMapperName, Profile, EntityFiles) = (nameSpace, autoMapperName, profile, entityFiles);


    }
}
