using System;
using Sample.AutoGenerated.HelperClasses.Interfaces;
using System.Collections.Generic;

namespace Sample.AutoGenerated.GeneratedStructure.ClassesGeneratedStructure
{
    public partial class EntitiesExtensionTemplate : ITextTemplate
    {

        /// <summary>
        /// Entity's Namespace.
        /// </summary>
        public string NameSpace { get; }

        /// <summary>
        /// Entity Files.
        /// </summary>
        public IEnumerable<string> EntityFiles { get; }

        /// <summary>
        /// Extension Name.
        /// </summary>
        public string ExtensiontName { get; }

        /// <summary>
        /// Creates an Instance of TableEntityTemplate.
        /// </summary>
        /// <param name="nameSpace">Entity's Namespace.</param>
        /// <param name="extensiontName">Extension Name.</param>
        /// <param name="entities">Entities.</param>
        public EntitiesExtensionTemplate(string nameSpace, string extensiontName, IEnumerable<string> entityFiles)
            => (NameSpace, ExtensiontName, EntityFiles) = (nameSpace, extensiontName, entityFiles);


    }
}
