using Sample.AutoGenerated.HelperClasses.Interfaces;
using System.Collections.Generic;

namespace Sample.AutoGenerated.GeneratedStructure.ClassesGeneratedStructure
{
    public partial class EntitiesContextTemplate : ITextTemplate
    {

        /// <summary>
        /// Entity's Namespace.
        /// </summary>
        public string NameSpace { get; }

        /// <summary>
        /// Entity Files.
        /// </summary>
        public IEnumerable<string> EntityFiles { get; }

        /// <summary>
        /// Context Name.
        /// </summary>
        public string ContextName { get; }

        /// <summary>
        /// Entity Configuration Convention.
        /// </summary>
        public string EntityConfigurationConvention { get; }

        /// <summary>
        /// Creates an Instance of TableEntityTemplate.
        /// </summary>
        /// <param name="nameSpace">Entity's Namespace.</param>
        /// <param name="contextName">Context Name.</param>
        /// <param name="entityConfigurationConvention">Entity Configuration Convention.</param>
        /// <param name="entities">Entities.</param>
        public EntitiesContextTemplate(string nameSpace, string contextName, string entityConfigurationConvention, IEnumerable<string> entityFiles)
            => (NameSpace, ContextName, EntityConfigurationConvention, EntityFiles) = (nameSpace, contextName, entityConfigurationConvention, entityFiles);


    }
}
