
using Sample.DataLayer.DataUtilities.Abstractions;
using Sample.DataLayer.DataUtilities.Interfaces;
using System.Collections.Generic;
using System.Linq;

namespace Sample.AutoGenerated.GeneratedUtilities.SystemConstants
{
    public class AutoGeneratedConstatnts
    {
        public class Projects
        {
            public const string UI_PROJECT_NAME = "Sample.UI";
            public const string BL_PROJECT_NAME = "Sample.BLLayer";
            public const string DATA_PROJECT_NAME = "Sample.DataLayer";
            public const string WEB_PROJECT_NAME = "Sample.Web";
        }
        public class FileConvention
        {
            public const string DEFAULT = ".cs";
            public const string DEFAULT_GENERATED = ".Generated.cs";
            public const string AUTO_MAPPER = "AutoMapperConfiguration.Generated.cs";
            public const string CONTEXT = "MainContext.Generated.cs";
            public const string CONTEXT_CONFIGURATION = "Configuration";
            public const string ENTITY_EXTENSIONS = "EntityExtensions.Generated.cs";
            public const string CONFIGURATION = "Configuration.cs";
            public const string CONFIGURATION_GENERATED = "Configuration.Generated.cs";
            public const string CONTROLLER = "Controller.cs";
            public const string VIEW_CONTROLLER = "ViewController.cs";
            public const string DTO_GENERATED = "DTO.Generated.cs";
            public const string DTO = "DTO.cs";
            public const string QUERY_SERVICE = "QueryService.cs";
            public const string INTERFACE_CONVENTION = "I";
            public const string MAPPING = "Mapping.cs";
            public const string MAPPING_GENERATED = "Mapping.Generated.cs";
            public const string REPOSITRY = "Repositry.cs";
            public const string UPDATE_SERVICE = "UpdateService.cs";
            public const string VALIDATING = "Validating.cs";
            public const string VIEW_GENERATED = "View.Generated.cs";
            public const string VIEW = "View.cs";
        }
        public class Folders
        {
            public const string MODELS = "Models";
            public const string ENTITIES = "Entities";
            public const string DATA = "Data";
            public const string ENTITY_DTOS = "EntityDTOs";
            public const string ENTITY_VIEWS = "EntityViews";
            public const string QUERY_SERVICES = "QueryServices";
            public const string MAPPING = "Mapping";
            public const string VALIDATING = "Validating";
            public const string UPDATE_SERVICES = "UpdateServices";
            public const string CONTROLLERS = "Controllers";
            public const string BL_UTILITIES = "BLUtilities";
            public const string INTERFACES = "Interfaces";
            public const string BASICS = "Basics";
            public const string REPOSITRIES = "Repositries";
            public const string EXTENSIONS = "Extensions";
            public const string CONFIGURATION = "Configuration";
            public const string GENERATED = "Generated";
            public const string DTOS = "DTOs";
            public const string VIEWS = "Views";
            public const string DATAUTILITIES = "DataUtilities";
            public const string DBCONTEXT = "DBContext";
        }
        public class FileClassName
        {
            public const string AUTO_MAPPER = "AutoMapperConfigurationGenerated";
            public const string CONTEXT = "MainContext";
            public const string ENTITY_EXTENSIONS = "EntityExtensions";
        }
        public class Attributes
        {
            public const string EXCLUDE_DTO_CONTROLLER = "ExcludeDTOController";
            public const string EXCLUDE_VIEW_CONTROLLER = "ExcludeViewController";
            public const string EXCLUDE_CONTROLLER = "ExcludeController";
            public const string STRING_LENGTH_ATTRIBUTE = "stringlengthattribute";
            public const string MAX_LENGTH_ATTRIBUTE = "maxlengthattribute";
            public const string MIN_LENGTH_ATTRIBUTE = "minlengthattribute";
            public const string ATTRIBUTE = "Attribute";
            public const string EXCLUDE = "Exclude";
            public const string COLUMN = "Column";
            public const string PROTECTEDPERSONALDATA = "ProtectedPersonalData";
            public const string PERSONALDATA = "PersonalData";
        }
        public class Paths
        {
            public const string DATA_ENTITIES = "Sample.DataLayer.Data.Models.Entities";
        }
        public class AutoGenerated
        {
            public const string ENTITIES_CONTEXT_TEMPLATE = "entitiescontexttemplate";
            public const string ENTITIES_EXTENSION_TEMPLATE = "entitiesextensiontemplate";
            public const string ENTITIES_AUTOMAPPER_TEMPLATE = "entitiesautomappertemplate";
        }
        public class NameSpaces
        {
            public const string SYSTEM = "System";
        }
        public class MetaDataTypes
        {
            public const string TEXT = "Text";
            public const string N_TEXT = "nText";
            public const string LONG = "Long";
            public const string INTEGER = "Integer";
            public const string DECIMAL = "Decimal";
            public const string DOUBLE = "Double";
            public const string BOOLEAN = "Boolean";
            public const string DATETIME = "DateTime";
            public const string DATETIMEOFFSET = "DateTimeOffset";
            public const string BYTE = "Byte[]";
            public const string LOOKUP = "LookUp";
        }
        public class BaseTypes
        {
            public const string BASEENTITY = "BaseEntity";
            public const string IBASEENTITY = "IBaseEntity";
        }
        public class IdentityEntities
        {
            public static readonly List<string> IDENTITY_ENTITIES_LIST = new List<string>() { USER,
                                                                                              ROLE,
                                                                                              USER_CLAIM,
                                                                                              USER_ROLE,
                                                                                              USER_LOGIN,
                                                                                              ROLE_CLAIM,
                                                                                              USER_TOKEN };
            public const string USER = "User";
            public const string ROLE = "Role";
            public const string USER_CLAIM = "UserClaim";
            public const string USER_ROLE = "UserRole";
            public const string USER_LOGIN = "UserLogin";
            public const string ROLE_CLAIM = "RoleClaim";
            public const string USER_TOKEN = "UserToken";
        }
        public class SystemTypes
        {
            public static readonly List<string> SYSTEM_TYPES_LIST = new List<string>() { STRING,
                                                                                         LONG,
                                                                                         INTEGER,
                                                                                         DECIMAL,
                                                                                         DOUBLE,
                                                                                         BOOLEAN,
                                                                                         DATETIME,
                                                                                         DATETIMEOFFSET,
                                                                                         BYTE};
            public const string STRING = "string";
            public const string LONG = "long";
            public const string INTEGER = "int";
            public const string DECIMAL = "decimal";
            public const string DOUBLE = "double";
            public const string BOOLEAN = "bool";
            public const string DATETIME = "DateTime";
            public const string DATETIMEOFFSET = "DateTimeOffset";
            public const string BYTE = "byte[]";
        }

        public class TypeScriptTypes
        {
            public static readonly List<string> TYPESCRIPT_TYPES_LIST = new List<string>() { STRING,
                                                                                             NUMBER,
                                                                                             BOOLEAN,
                                                                                             DATE,
                                                                                             ANY};
            public const string STRING = "string";
            public const string NUMBER = "number";
            public const string BOOLEAN = "boolean";
            public const string DATE = "Date";
            public const string ANY = "any";
        }

        public class SystemList
        {
            public static List<string> BASE_ENTITY_PROPERTIES { get; set; } = typeof(BaseEntity<long>).GetProperties().Where(s => s.DeclaringType.Name == typeof(BaseEntity<long>).Name).Select(s => s.Name).ToList();
            public static List<string> IBASE_ENTITY_PROPERTIES { get; set; } = typeof(IBaseEntity<long>).GetProperties().Where(s => s.DeclaringType.Name == typeof(IBaseEntity<long>).Name).Select(s => s.Name).ToList();
        }
        public class Other
        {
            public const string ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            public const string DOT = ".";
            public const string PATH_DASH = "\\";
            public const string COMMA = ",";
            public const string LEFT_BRACKET = "(";
            public const string RIGHT_BRACKET = ")";
            public const string LEFT_SQUARE_BRACKET = "[";
            public const string RIGHT_SQUARE_BRACKET = "]";
            public const string LEFT_TRI_BRACKET = "<";
            public const string RIGHT_TRI_BRACKET = ">";
            public const string REMOVE_LINE = "removeline";
            public const string IES = "ies";
            public const string Y = "y";
            public const string S = "s";
            public const string QUESTION_MARK = "?";
            public const string NINE_SPACES = "         ";
            public const string FOUR_SPACES = "    ";
            public const string COMMA_WITH_SPACE = " ";
            public const string UPPER_COMMA = "`";
            public const char UNDER_SCORE_CHAR = '_';
        }

    }
}
