using System;
using System.Collections.Generic;

namespace Sample.AutoGenerated.GeneratedStructure.T4GeneratedInterfaces
{
    interface IT4GeneratedEntities
    {
        public void Generate(IEnumerable<string> entityFiles, string folderName);
    }
}
