using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sample.AutoGenerated.GeneratedStructure.T4GeneratedInterfaces
{
    public interface IT4GeneratedEntitiesAutoMapper
    {
        public void Generate(IEnumerable<string> entityFiles, Type profile, string folderName);
    }
}
