using Sample.AutoGenerated.HelperClasses;
using System;

namespace Sample.AutoGenerated.GeneratedStructure.T4GeneratedInterfaces
{
    public interface IT4GeneratedSingleEntity
    {
        public void Generate(string tableName, TableInfo tableInfo, string folderName);
    }
}
