using System;
using System.Collections.Generic;
using Sample.AutoGenerated.HelperClasses;

namespace Sample.AutoGenerated.GeneratedUtilities.HelperClasses
{
    public class T4GeneratedArguments
    {
        public TableInfo TableInfo { get; set; }
        public List<Type> Entities { get; set; }
        public string Path { get; set; }
        public string NameSpace { get; set; }
        public bool IsAlwaysGenerated { get; set; } = false;
        public Type Class { get; set; }
        public string GeneratedClassName { get; set; }
        public string EntityConfigurationConvention { get; set; }
        public Type Profile { get; set; }
        public IEnumerable<string> EntityFiles { get; set; }

    }
}

