using System;
using System.Collections.Generic;
using System.Xml.Linq;

namespace Sample.AutoGenerated.HelperClasses
{
    public class TableInfo
    {
        public string BaseType { get; set; }
        public string IdType { get; set; }
        public string IdTypeSciptType { get; set; }
        public bool IsBaseIdPrimaryKey { get; set; }
        public string Name { get; set; }
        public IEnumerable<XAttribute> TableAttributes { get; set; }
        public IEnumerable<string> EntityFiles { get; set; }
        public IEnumerable<XElement> Properties { get; set; }
        public Type Context { get; set; }
        public Type ServiceBuildException { get; set; }
        public Type CommonServices { get; set; }
        public Type PaginationHelperServices { get; set; }
        public Type Mapper { get; set; }
        public Type UriService { get; set; }
        public Type SystemServiceProvider { get; set; }
        public Type ApiExceptionBuilder { get; set; }
        public Type Profile { get; set; }
        public Type ICacheProvider { get; set; }
    }
}
